<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USL-2T59152" failures="2" tests="2" name="testmethods.PricingModuleTest" time="179.802" errors="0" timestamp="28 Apr 2022 06:06:42 GMT" skipped="0">
  <testcase classname="testmethods.PricingModuleTest" name="verifyPricingDecimalPlaces" time="72.899">
    <failure message="verifyPricingDecimalPlaces failed :Index 1 out of bounds for length 1" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: verifyPricingDecimalPlaces failed :Index 1 out of bounds for length 1
at org.testng.Assert.fail(Assert.java:96)
at testmethods.PricingModuleTest.verifyPricingDecimalPlaces(PricingModuleTest.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyPricingDecimalPlaces -->
  <testcase classname="testmethods.PricingModuleTest" name="verifyItemPriceAfterLoginInDetailPage" time="106.903">
    <failure message="verifyItemPriceAfterLoginInDetailPage failed :Item Price is not displayed. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: verifyItemPriceAfterLoginInDetailPage failed :Item Price is not displayed. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at testmethods.PricingModuleTest.verifyItemPriceAfterLoginInDetailPage(PricingModuleTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyItemPriceAfterLoginInDetailPage -->
</testsuite> <!-- testmethods.PricingModuleTest -->
